development:
  adapter: sqlite3
  encoding: unicode
  database: pizzashop_dev
  pool: 2
  username: gur
  password: 123

production:
  adapter: sqlite3
  encoding: unicode
  database: pizzashop_prod
  pool: 2
  username: gur
  password: 123